#JOB & STAGE name shold not have any spaces
#default azure runs stages parallely, to make it sequential we should write condition

#trigger:
#- main

pool: Default

variables:
  COMPONENT: user

resources:
  repositories:
  - repository: templates
    type: github
    name: devopsravi9/robo-azure-devops-template
    endpoint: devopsravi9

stages:
- template: nodejs.yml@templates








